### ISSUE TITLE
Oculus Quest controller model and position offset

### ISSUE THREAD

**Issue by nskolaris** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#11]
The controller rotation was fixed a couple of versions ago but the position is still off by a few centimeters.
Solutions like ALVR and Virtual Desktop also use the Rift S/Quest controller model in SteamVR, using the appropriate model would make it also easier to verify the controller position is right.

Thanks for providing this great feature!

**Comment by GennadiyAMD** [comment]
@nskolaris - the absolute majority of games ignore the default render model provided by SteamVR and draw their own controllers. Even SteamVR Home draws its own. The only time when you would see the default render model is in SteamVR startup view (what you see while the game is loading) and when you press the Menu button on the left controller. Games would have to change to draw the Quest controllers instead of Touch. And because games use their own render models, the controller position depends on the game. It's easy to see if you own any of the "Serious Sam" titles. Turn the controllers to face each other and bring them together until they touch. In SteamVR Home they would appear to be 5-10cm apart while in Serious Sam they would almost touch each other. So offsetting them by a fixed amount would improve some titles and break others - no universal fix here unfortunately.

Thanks for the feedback!

**Comment by nskolaris** [comment]
Thanks for the response.
I understand games don't use the default controller model and it's only seen in the SteamVR menu interface, the model is not really the problem. 
Some games may shift the controller position, but most seem to be using the default position as seen in the SteamVR menu, using Relive when you look at your real controllers and the ones in vr their position differs by around 4-5cm. ALVR and Virtual Desktop manage to render the controllers in the same position as your real ones.
This issue causes the user to sometimes smash their controllers between each other and cause loss of presence, I think making the controller position match in the steamvr menu environment would enhance the experience in most games.

**Comment by RaymondWeilacher** [comment]
For Quest users, would it be possible for Relive to tell games that we're using the Rift S controllers rather than CV1? Games like H3VR, which show different controller models depending on what you are using, currently show the Touch controls.

**Comment by GennadiyAMD** [comment]
@nskolaris - please update to 1.0.15 - moved the controllers forward and upwards to match Oculus Rift CV1. Also don't forget to update the driver to Adrenalin 19.8.1 to fix the haptics problem.

**Comment by nskolaris** [comment]
@GennadiyAMD I just tested 1.0.15 together with latest driver.
Position is now much better, but there is a strange issue causing the virtual controllers to snap their rotation/position when holding them at certain angle. I can upload a video to provide a better explanation later.

Thank you!

**Comment by GennadiyAMD** [comment]
@nskolaris - please try 1.0.16.

Thanks for catching this!

**Comment by nskolaris** [comment]
@GennadiyAMD Position is perfect now.

Thank you!
Closing this issue
