### ISSUE TITLE
How can we see ingame performance inside headset ?

### ISSUE THREAD

**Issue by patientx** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#110]
:: system :: (ryzen 3600x - rx 480 gb - 16 gb ddr4-3000 - oculus quest 2)
Having a rx480 , was looking for alternatives for wireless streaming and came across this , looks great works great at first glance but 
...
In other methods (oculus link, airlink and alvr) all essentially work through oculus software so I can see game performance inside vr so I can make adjustments and decide which settings should be lower or higher etc. But with relive-vr, the only method I can use ,oculus' own OVRMetricsTool which I install on the device itself, only shows the "video framerate I get" rather than the real performance of the game. Is there a way I can see realtime fps of the running program inside headset like oculus own performance monitor tool ?

**Comment by GennadiyAMD** [comment]
@patientx - which parameters of a game are you trying to tune?
The "video framerate I get" reported by OVRMetricsTool is actually a good measure as it does show the true frame rate. It measures it at the point of presentation, at the very end of the pipeline, so it is a good starting point. Encoding and decoding times are fairly constant and depend on pretty much the resolution alone. You can get these numbers from the AMDWirelessVR.log file in the Steam's log folder (c:\Program Files (x86)\Steam\logs).

Since there is no video buffering anywhere in the pipeline, the final framerate measured by OVRMetricsTool would reflect the frame rate produced by the game. The image quality would be mostly defined by the bitrate - if your network can handle 100Mbps with no hiccups, by all means, put it to High in Radeon Settings. Usually the only titles that would show some stutter due to that are games with motion that is not related to head movements (think rollercoaster-type games) - they typically perform better at 50Mbps as network latency is a bit more stable with lower amount of traffic.

Other than that, it's really a balance between a higher resolution (rendering and encoder) and latency. Higher encoder resolution means more time to encode and decode and will result in slightly higher latency, but a crispier image. Non-linear encoding set to true helps alleviate this somewhat - 1440x1440 per eye with non-linear encoding on would look similar to 1600x1600 without non-linear scaling.

Since you have an older card (RX480), you have to use HEVC for encoding and 1472x1472 per eye encode resolution is your limit @72fps. You might have to go a little lower if you want to run at 90fps. On these cards the encoder was the bottleneck - anything Navi (RX5600 or newer) would perform way better.

Hope this helps!

**Comment by patientx** [comment]
> Since you have an older card (RX480), you have to use HEVC for encoding and 1472x1472 per eye encode resolution is your limit @72fps. You might have to go a little lower if you want to run at 90fps. On these cards the encoder was the bottleneck - anything Navi (RX5600 or newer) would perform way better.
> 
> Hope this helps!

Are these settings OK ? Also , since device is capable of up to 120hz should I limit max framerate to for example 72 if I want to target that ?

![relivevr](https://user-images.githubusercontent.com/5392772/126231290-dcc4b2fe-e43d-42fc-b85c-8ff21f189f76.png)

**Comment by GennadiyAMD** [comment]
@patientx - Your FOV of 85 degrees is too narrow, the device's FOV is about 100 degrees and you want to go wider than that do minimize the appearance of black margins when you turn your head quickly. I'd set it to 101-104 degrees. You should also be able to bump up the resolution to 1440x1440 on these cards.

Frame rate shown in SteamVR is also accurate as we pace the game to what the encoder and the headset can handle.

Default settings are actually pretty optimal for RX480/580/590 cards as they're really the lowest common denominator for wireless VR - we tried to make sure that they worked out of the box. Newer GPUs, especially Navi, can do much better - either achieve lower latency or higher resolution. Polaris was a good match for the original, first generation Quest, but if you want to use Quest2 to its full potential, RX5600 is the minimal spec. There's really no magic to it ;)

**Comment by patientx** [comment]
I kept insisting about trying to learn the fps in game because I couldn't believe I was getting this crisp image with this seemingly high performance.  Now I see somehow using steamvr with relive really helps a lot.

I looked at AMDWirelessVR log file and can see while it sometimes drops a few fps lower , it maintains 72 fps most of the time. I am sure I wasn't getting this type of performance with oculus link or airlink (Borderlands 2 VR) 

Thanks for the help and keep up the good work.
