### ISSUE TITLE
Using OpenVR Space Calibrator

### ISSUE THREAD

**Issue by quigonwhiskey** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#124]
When using Relive VR, I'm connecting fine but have an issue in OpenVR Space Calibrator. I'm not sure if the issue lies with that app or this one, but I see on one panel a driver for "AMD Redirect" in the /hmd directory. If i switch to the oculus device list it lists 2 rift s controllers (using Quest 2). This will not allow the calibration with vive trackers because it detects no hmd. I believe the HMD is in the AMD driver list however, it requires a controller to do the calibration. Not sure if its possible to pass the HMD through to the Oculus driver, or maybe include controllers in the AMD device? If this is an issue that should be corrected by OpenVR space calibrator, I appologize for wasting your time. The tool works with Virtual Desktop but I'd prefer to use your driver if this can be achieved somehow. Thank you

**Comment by nickking93** [comment]
Updating for anyone who may see this: this seems to have either been fixed in the latest adrenaline driver, or I caused the issue myself by disabling oculus runtime. Doing so worked fine in virtual desktop but steam Vr seems to crash when disable in relive Vr. Enabling it and setting oculus as default has allowed it to work and register the hmd with my controllers in open space calibrator. I'm excited to make the switch from virtual desktop now that I can use full body tracking.
