### ISSUE TITLE
[AMFEncoderHEVC]    Info: SubmitInput() Input Queue Full:3 error in log file

### ISSUE THREAD

**Issue by patientx** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#129]
PC specs : rx 570 i5 16 gb ram oculus quest 2 
installed latest beta version apk on quest 2 , using hevc also , tried to lower bitrate to 40 mbit, resolution to 1180x1180 and yet this error pops up and dont see game on quest 2. Gpu driver is latest one 2022.2.3. 

Thanks.

**Comment by GennadiyAMD** [comment]
@patientx  - could you please attach the AMDWirelessVR.log file? Thanks!

**Comment by patientx** [comment]
[AMDWirelessVR.zip](https://github.com/GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR/files/8165123/AMDWirelessVR.zip)

**Comment by patientx** [comment]
it was 64 mb so I zipped it

**Comment by lev-kisselman-amd** [comment]
@patientx what was the name of the APK you installed?   
ReLive-VR.2.0-beta.apk or ReLiveVR-Oculus-1.0.26.apk

**Comment by lev-kisselman-amd** [comment]
Hi @patientx 

Looking at the log, this is the line that's (likely) the issue
>>SendMessage() took 111.72 
that's why encoder queue is full and that's why VideoPipeline is dropping frames.  

1) Tell me, what is your router model and network setup? 
2) Make sure to
 - use good router
 - connect server to router through ethernet
 - verify Oculus has great connection wifi connection

**Comment by patientx** [comment]
Thanks, it was a friends actually and I suspected the router as well. We
are gonna buy a better one.
