### ISSUE TITLE
how to setup a second wireless router?

### ISSUE THREAD

**Issue by BrotherO4** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#20]
must be a stupid question. my setup is as follow. pc to a network switch than to my modem(which is a wireless router.) this works but its not close by. so i was trying to plug my second router to the switch so it can be within my room. this does not work. is there something i am missing?

**Comment by GennadiyAMD** [comment]
Your PC and your headset need to be on the same IP subnet for them to be able to find each other. You have two options:
1 - PC connected to a LAN port of your second router and headset connecting to the second router's SSID. The WAN port of the second router is connected to a LAN port of your main router that provides internet access. The downside of this setup is that your gaming PC will not be visible to devices connected to the main router. You will also need to make sure that the LAN subnets of the two routers are different - some routers will take care of that automatically.
2 - disable DHCP server in one of the routers, so that there's only one DHCP server on the network and connect their LAN ports together. Leave the WAN/Internet port of the second router disconnected. Your PC can be connected to either router - the difference in latency would be negligible. Your second router would be acting like a switch and an access point. This would be my preferred configuration.
In either case, do not make the SSID the same on both routers to avoid AP hopping. Pair the headset only with the SSID of the router you intend to use for VR.

Makes sense?

**Comment by BrotherO4** [comment]
i fix the issue. it seems it was related to resolution.
second question. i notice the lag was worse than other wireless methods. is
there a way to improve it?

**Comment by BrotherO4** [comment]
would this work for my setup? i am not able to reach my router. what i can reach is my lan switch. my setup is as follow my modem/router into my lan switch. my pc, pc, and second router. would that effect your advice?

**Comment by BrotherO4** [comment]
oyu know what. i changed game and the slight stutter is gone. so i can run my games at 100 mbps bitrate no issue. i guess the one wall is not doing anything at all to me. i guess its a pavlow thing.

**Comment by BrotherO4** [comment]
that right there did the trick. it worked.
now i did the rest again..most of the stutter in this game seems to be almost completely gone at 100mps and slightly less at 50 mbps. thanks..i think you should post this how to on the main just in case others would like to do the same through a switch.

i got a few questions but its nothing about issues. just kinda want to know geeky shit.
does Relive support A Warp? if not you think it be possible to add such a feature in the future?
also have you guys thought about doing something similar like what Oculus link is doing. rendering the outside less so but keeping the middle close. if you have what kind of issue you all ran into or is it even possible?

**Comment by GennadiyAMD** [comment]
@BrotherO4 - what do you mean by "A Warp"? Asynchronous Timewarp? If yes, of course we're doing it, along with many other tricks to reduce/hide latency - otherwise we'd be hugging porcelain every 10 minutes :)

Rendering less on the periphery, this is called "foveated rendering" btw, we can't do it at the place where we are in the whole pipeline - by the time we get a frame, it's already rendered at whatever resolution a game decided to render it. Oculus can do it because they control more of the rendering pipeline. So this is really a question to game developers themselves and game engines and as far as I know, some engines do support it. If a game supports foveated rendering, then it would be transparent to us.
