### ISSUE TITLE
GearVR not working without controller 

### ISSUE THREAD

**Issue by imilanov** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#40]
Hi,

I have a problem with ReLiveVR-Oculus-1.0.20.apk, everything working good, it's connected with Steam VR (Motion working) but on GearVR screen is only GearVR controller with small red x. I purchased my GearVR set without controller and i'm unable to use your great app. Can you please find way how it can work, like in Riftcat VR?

Best Regards,
Ivan

**Comment by GennadiyAMD** [comment]
@imilanov - how are you planning to navigate in VR without a controller? Xbox-style gamepad?

**Comment by imilanov** [comment]
@GennadiyAMD xbox game pad is recognized as official controller in SteamVR, also navigation on GearVR (integrated touchpad and buttons) are enough functional for simple navigation in SteamVR environment (*can be develop).

**Comment by GennadiyAMD** [comment]
@imilanov - please try [version 1.0.21](https://github.com/GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR/blob/master/ReLiveVR-Oculus-1.0.21.apk)

Unfortunately we cannot utilize the touchpad on the GearVR headset in SteamVR since there's no equivalent there. But the app will now connect regardless of whether you have the hand controller or not and you can use an Xbox-style controller connected to the PC with titles that support it.

Please let us know how it's working out for you.

**Comment by imilanov** [comment]
I installed the apk but it crash with "Thread Priority Security Exception on Gear VR" message.

**Comment by GennadiyAMD** [comment]
@imilanov - did you inject the Oculus signature before installing the apk? Please follow the instructions for GearVR sideloading on this [Wiki page](https://github.com/GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR/wiki/Setting-up-ReLive-VR)

**Comment by imilanov** [comment]
Confirmed, works good! Thank you!
