### ISSUE TITLE
Feature Request:  Ability to manual configure Scaling force

### ISSUE THREAD

**Issue by romanpekarskiy** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#42]
Guys, first of all i want to tell you are awesome! I have checked recent update of Relive VR and was so happy with web interface settings and ability to non-linear scale image!
And i have found there also FOV settings available - i have tried to reduce FOV to something like 50x50 degrees, and i was shocked what impact that makes on image quality - it was night and day in Elite: Dangerous. I think image looks much crisper than Oculus Quest native homescreen!
But, obvious FOV was kinda low, i'm OK to play like that in Elite, and i prefer that image clarity much much more than blurry 100 FOV image.
I have noticed that image was a little pixelated on edges on that "window" rectangle caused by non-linear scaling - but it look barely noticable.

So, my request is about to add some setting to confugure force of scaling, i think if there was option to have 100 FOV with poor pixelated quality image in peripheral, but a good crisp quality in center (like i've described above when setting FOV to 50 with resolution 1280x1280) it will be really great. I think i will be totally OK to have pixelated trash image on peripherals, still better than pitch black. Is that possible? Or, may be, there already exist some setting to configure scaling force?

Thank you guys

**Comment by quakemazer** [comment]
Wow. I just tried this and the clarity in the middle of the image is amazing. It seems like they could indeed do what you are requesting. I actually thought that was the whole point of foveated rendering, to make it sharp centrally and pixelated at the edges (far more pixelation than what happens currently in Relive, in order to give a more drastic performance boost).

Nvidia's contrast preserving foveated rendering mode ( https://youtu.be/lNX0wCdD2LA?t=64 ) would be exactly what we need here (minus eye-tracking of course).

The sharp image in the center with fov setting lowered is astounding.

As for the user interface side of this setup. You could simply have a box in the center of your overall resolution  that you could resize visually in the setup screen (say with a red box you can drag or enter numbers as you choose).

Finally I just want to thank AMD for Relive VR Streaming. It's the best solution I've found for PCVR on my Quest.
