### ISSUE TITLE
Issues after Steam VR update 1.10.22

### ISSUE THREAD

**Issue by NPCarl** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#45]
Had everything working great on my quest yesterday. Today, when i get into SteamVr it is so laggy its really unplayable. The only thing that i know has changed is that SteamVR updated version. Is anyone else experiencing problems after this latest update?

**Comment by NPCarl** [comment]
My specific problem is the image lagging behind head movement. I have ruled out the possibility of the problem coming from my router, as the problem persists even when connected directly to the PC's hotspot.

**Comment by GennadiyAMD** [comment]
@NPCarl - I'm running SteamVR 1.10.22 on two different systems (including a Ryzen 7 3750H laptop) and not seeing any difference in performance compared to previous versions. So I don't think your problem is related to this SteamVR update. 

Please try the suggestions in the [Troubleshooting Wiki page](https://github.com/GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR/wiki/Troubleshooting#image-lags-behind-head-movements)

Please attach the AMDWirelessVR.log file located in c:\Program Files (x86)\Steam\logs so that we could see what is going on.

**Comment by GennadiyAMD** [comment]
@NPCarl - has this issue resolved itself for you? It could've been as simple as Windows deciding to download updates at the same time...
