### ISSUE TITLE
Audio delay

### ISSUE THREAD

**Issue by Clavus** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#5]
I've been playing a few SteamVR games with my Quest, and I noticed there's a noticable delay in the audio streaming (about 0.5 to 1 second). My desktop was also still playing the audio so it was easy to hear. The delay is far greater than that of the visuals and force feedback signal on my controllers (while firing a gun in the VR game Arizona Sunshine).

**Comment by RaymondWeilacher** [comment]
I'm having the same issue. I have a similar audio delay using ALVR, you? This might be a problem with all the streaming solutions.

**Comment by Cerv4ntez** [comment]
is there a way to disable audio streaming to the headset? I tried setting channels to 0 in settings.json but it did not work. I'm OK with the sound coming from my pc when streaming and the bandwidth saved would be a small bonus

**Comment by GennadiyAMD** [comment]
@Clavus , @RaymondWeilacher - thanks for reporting this issue. We have done some optimizations in both the headset and the driver, please make sure to update the driver to Adrenalin 19.7.3 (posted on the AMD web site on July 25) and update the ReLive VR app to version 1.0.13.
Please keep the following in mind though:
- The goal is to keep audio in sync with video in the headset. Because there's some latency overall, the audio coming out directly from the PC would be ahead of video in the headset and hearing some delay between the sound coming from the headset and the PC directly is normal.
- Audio coming out of the headset has some unavoidable delay relative to the video as at least some minimal buffering on the receiving end is needed to avoid sound break-up due to variable network latency.  

@Cerv4ntez - we will add a configuration option to turn off audio streaming in one of the future driver updates.
