### ISSUE TITLE
Sideloading onto Quest Not Working (adb error)

### ISSUE THREAD

**Issue by etscott** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#51]
I followed the instructions. Quest is in Developer Mode, and SideQuest works fine. Guidance would be apprecitaed.

SDK Platform Tools is version 30.0.0, ReLive apk is version 1.0.23.

When I execute the adb install command, I get the following error:

`C:\Users\Edward\Downloads\platform-tools>adb install -r ReLiveVR-Oculus-1.0.23.apk`
`Performing Streamed Install`
`adb: failed to install ReLiveVR-Oculus-1.0.23.apk: Failure [INSTALL_PARSE_FAILED_UNEXPECTED_EXCEPTION: Failed to parse /data/app/vmdl1771038967.tmp/base.apk: AndroidManifest.xml]`

**Comment by quakemazer** [comment]
Not sure about the issue there, but you can just use SideQuest itself to install the apk.

**Comment by etscott** [comment]
I tried using SideQuest to install the apk and got the same error. What's going on here? I'd really like to try ReLive...

`A task failed. Check the tasks screen for more info. ReLiveVR-Oculus-1.0.23.apk: : Command failed:
"C:\Users\Edward\AppData\Roaming\SideQuest\platform-tools\adb.exe" -s 1PASH9AK020142 install -r -d 
"C:\Users\Edward\Downloads\ReLiveVR-Oculus-1.0.23.apk" adb: failed to install C:\Users\Edward\Downloads\ReLiveVR-Oculus-1.0.23.apk: Failure [INSTALL_PARSE_FAILED_UNEXPECTED_EXCEPTION: Failed to parse /data/app/vmdl508854316.tmp/base.apk: AndroidManifest.xml]`

**Comment by GennadiyAMD** [comment]
@etscott - sounds like the apk was corrupted during download. I've just tried downloading it from Github and installing it and it worked fine, so it's intact here. Try re-downloading it.

**Comment by etscott** [comment]
So I had tried redownloading just the apk and got the same result, but I just cloned the repo and using that apk seems to have worked. Not sure what the issue was with my download, but definitely user error it seems. Consider the issue closed.

Thanks!

**Comment by GennadiyAMD** [comment]
@etscott - very interesting! I don't have a good explanation of what is happening, but just found a similar report for a different app on Reddit: https://www.reddit.com/r/OculusQuest/comments/cxc1iv/every_time_i_try_to_download_dogcorp_i_get_this/

Turned out that some ISPs apply "child locks" by default and alter a zip file during download from what the thread is saying. This kind of makes sense - when you do 'git clone', they might not consider it browser traffic and don't apply their "safe browsing" rules. When you cloned the repo, which protocol did you use, https or ssh? The user who reported the above was able to work around it with VPN - if you have some kind of VPN connection, might be worth trying.

Also, you might want to do a binary comparison on the file you downloaded with the file from the cloned repo: `fc /b <path to apk1> <path to apk2>` on the command line or, since apk are just zip files, you can open it with something like 7-Zip to see if your ISP doing something to them. This might give you some idea of what is going on.
