### ISSUE TITLE
Certain Games Don't recognize Oculus Rift S/CV1 Controller Emulation

### ISSUE THREAD

**Issue by JpTiger** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#59]
I'm using an Oculus Quest Headset with version 1.0.23 of the Relive apk, and Adrenalin and Drivers v 20.5.1 for my Radeon RX 480 card. Mostly it works fine, but for at least two games, even though I have it set to emulate an Oculus Rift S (and third party controllers disabled), the game shows Vive controllers. Both games support Oculus controllers, but they don't seem to recognize them as such when launched via Steam Home. The issue persists if I try emulating Rift CV1 instead. The games are [Keep Talking and Nobody Explodes](https://store.steampowered.com/app/341800/Keep_Talking_and_Nobody_Explodes/) and [Transpose](https://store.steampowered.com/app/835950/Transpose/). 

Log attached here:
[AMDWirelessVR.log](https://github.com/GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR/files/4867059/AMDWirelessVR.log)

If it's helpful, Keep Talking and Nobody Explodes also generates a log file, here's what looks like the relevant error it gives:
```
Checking device 1 (Controller (XBOX 360 For Windows))
Device 1 (Controller (XBOX 360 For Windows)) matched profile "Xbox360WinProfile" (Xbox 360 Controller) but is HIDDEN and will not be attached.
Checking device 2 ()
Checking device 3 ()
Change in attached Unity joysticks detected; refreshing device list.
Checking device 1 (Controller (XBOX 360 For Windows))
Device 1 (Controller (XBOX 360 For Windows)) matched profile "Xbox360WinProfile" (Xbox 360 Controller) but is HIDDEN and will not be attached.
Checking device 2 (OpenVR Controller(Oculus Rift S (Left Controller)) - Left)
[KTInputManager] Device attached: Unknown Device ("OpenVR Controller(Oculus Rift S (Left Controller)) - Left") [Supported] [Platform: WINDOWS 10 PRO 64BIT BUILD 18363]


[InControl] Joystick 2: "OpenVR Controller(Oculus Rift S (Left Controller)) - Left"
Device 2 (OpenVR Controller(Oculus Rift S (Left Controller)) - Left) does not match any supported profiles and will be considered an unknown controller.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Checking device 3 (OpenVR Controller(Oculus Rift S (Right Controller)) - Right)
[KTInputManager] Device attached: Unknown Device ("OpenVR Controller(Oculus Rift S (Right Controller)) - Right") [Supported] [Platform: WINDOWS 10 PRO 64BIT BUILD 18363]


[InControl] Joystick 3: "OpenVR Controller(Oculus Rift S (Right Controller)) - Right"
Device 3 (OpenVR Controller(Oculus Rift S (Right Controller)) - Right) does not match any supported profiles and will be considered an unknown controller.
```

Games that seem to recognize the Oculus controllers correctly include Steam Home and The Lab. Thumper may as well, but it's difficult to say for certain as the controllers are never shown - functionally it works fine.

**Comment by GennadiyAMD** [comment]
@JpTiger - this seems to be the same as described [here](https://github.com/GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR/issues/82). Some games try to go the Oculus API directly, bypassing OpenVR when they see an Oculus headset. Superhot was a good example of this, at least at some point - you could even kill SteamVR after launching it, but the game would keep running. 

There isn't much we can do about this, unfortunately. If you're getting these games from the Oculus Store rather than Steam, running them under Revive might help.

**Comment by JpTiger** [comment]
I'm actually fairly sure this is a different issue, though it might have the same root cause. Unlike [Issue #82 ](https://github.com/GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR/issues/82) the games launch just fine for me in SteamVR mode to my headset. They just think that I'm using Vive controllers instead of Oculus controllers.

Can you say a little more about how Revive might be a workaround? I hadn't tried that because I assumed it would still think (even more so) that I was using Vive controllers instead of Oculus ones.

**Comment by GennadiyAMD** [comment]
@JpTiger - Revive implements the native Oculus API on top of SteamVR. Games launched under Revive think they're running on Oculus natively rather than on SteamVR. The downside of Revive is that it only works with games from the Oculus Store.

The whole problem arises from the fact that game developers want to distribute the same game through both Steam and Oculus store, but don't want to maintain two versions of it or two different code paths for Oculus headsets. Obviously a game in the Oculus Store cannot rely on SteamVR being there, so they go directly to the Oculus API for controllers and display. For Vive SteamVR is the only choice they have and SteamVR has the driver for Oculus that translates OpenVR calls to the Oculus API calls. But for this to work the Oculus runtime has to be present on the PC, so games have the choice of OpenVR or Oculus native API and some choose to go Oculus native when they detect an Oculus headset.

ReLive VR pretends to be a Rift S or a CV1, but it doesn't rely on the Oculus run-time. Games see an Oculus device, attempt to use the Oculus native API, but it fails because the Oculus run-time is looking for the physical device on USB and/or HDMI and fails, hence the game gets stuck. So a nice way for the games would be to try the Oculus API first and if it fails, fall back to OpenVR, most do this, but some don't.

Does this make sense?

**Comment by JpTiger** [comment]
I appreciate the thoroughness of the explanation but I don't think I quite have the technical background to totally follow it. Regardless, I've tried installing ReVive, and while I can now access Oculus apps like the DreamDeck, which is kind of neat, the issue persists in the games above- controllers are still detected as Vive controllers. I can add that this is also true in the game Interkosmos, but not the game I Expect You To Die, both purchased on Steam.

I'd don;t think this issue is resolved, what would the next steps be? Contact game developers individually? And if so, what information should I give them? I've reached out to a couple and they seem stumped so far.

**Comment by GennadiyAMD** [comment]
[AMD Official Use Only - Internal Distribution Only]

Hi Joel,

Yes, I agree that the issue is not resolved, the problem is that it is impossible to resolve it from our end - the issue lies with the games themselves. Contacting game developers is your best bet.

As to what you should tell them, aside from describing the issue itself - hard for me to tell because I don't know what the game is doing as i don't have its source code. The game developers would have to try to run the game using ReLive VR instead of a real Rift S and debug it. Please feel free to quote my previous explanations to them, with the caveat that they were only guesses, of course. If you get their attention,  they're more then welcome to contact me directly either here on Github, or via email gennadiy dot kolesnik at amd dot com (replace 'dot' with . and 'at' with @ ) - we would be happy to assist them.

Regards,
Gennadiy

________________________________

**Comment by JpTiger** [comment]
Thank you very much! I'll see what I can do. I wonder if it's an underlying platform issue with something like Unity...
