### ISSUE TITLE
Incorrect and inconsistent framerate value reported in SteamVR

### ISSUE THREAD

**Issue by DrNeroCF** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#64]
I keep revising Relive since the last two AMD drivers haven't worked with Oculus Link, and I'm trying to figure out if it's possible to have a stutter-free experience wirelessly.  All my hardware should be up to task (5700tx, ac router, 9700k), but I still haven't been able to get as smooth of an experience as with Oculus Link.

The framerate always seems to be wrong, and inconsistent (as off as 66hz, 75hz has been the closest, I may have seen the Quest's 72hz once?

I'm hoping the stutter is coming from something simple like an incorrect framerate, instead of a completely smooth experience over wireless just being impossible.

**Comment by GennadiyAMD** [comment]
@DrNeroCF - could you elaborate more on where and when you see stutter? Is it controllers, is it a certain type of motion, or certain type of animation? It is very hard to tell what the problem is without seeing it, so please provide as many details as possible. It would also be very helpful if you could attach a log file located at c:\Program Files (x86)\Steam\logs\AMDWirelessVR.log - just play whichever title you think is causing problems for a few minutes and then attach this file to this thread.

Frame rate can fluctuate depending on many factors, like the complexity of a scene, for instance. Are you comparing ReLive VR to Oculus Link under the same conditions (running the same game under Steam)?
