### ISSUE TITLE
No VR settings in AMD Radeon software

### ISSUE THREAD

**Issue by JakeHasSkill** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#68]
In my Radeon settings, there isn't a VR streaming section. In program files/AMD, there is no WVR folder. The AMD Radeon software says my computer meets the minimum requirements to run SteamVR, and I've used oculus link to run SteamVR before.
I have an AMD Radeon R9 270, an Intel core i7-7700 @3.60GHz and 4 cores, and 16 GB of ram.

**Comment by GennadiyAMD** [comment]
@JakeHasSkill - R9 270 is a very old GPU and is not VR-capable. It came out back in 2013, before any VR came to be, let alone wireless. The encoder there is way too slow to give you any decent frame rate. That's why we are not even installing ReLive VR on these cards - you'd not have a good VR experience on them, especially wirelessly.

The minimum spec for ReLive VR is RX470. Any discrete GPU newer than this (excluding only RX550) should be fine. RX470, RX480, RX580, RX590, Vega, Radeon VII... Best choice today would be RX5700 or RX5600. Even RX5500 would work.

Hope this helps.
