### ISSUE TITLE
"Oculus Rift and Rift S only supported in native mode" when booting Walking Dead: Saints and Sinners

### ISSUE THREAD

**Issue by overdrive-ostrich** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#73]
I recently purchased Walking Dead: Saints and Sinners and, upon booting through ReLive, found that it would not run. While I couldn't find much regarding my specific issue, it looks like something similar happened to Virtual Desktop users--until there was eventually a fix. Something about the game checking and seeing I'm not running a "native" Oculus headset and therefore quits the game.
 Is that something we can see in a future update? Or is there some kind of workaround?

**Comment by GennadiyAMD** [comment]
@overdrive-ostrich - your only workaround option with ReLive VR is to emulate a Vive headset instead of Oculus. The downside is that controller button mappings will be odd because Vive and Oculus controllers are very different. If you choose to go this route, change the headset emulation type in Radeon Software, just a few lines below the flip switch that controls SteamVR integration for ReLive VR. Don't forget to restart SteamVR after changing the headset type if you do this while SteamVR is running.

We cannot comment on the new features and/or future development plans, sorry.

**Comment by overdrive-ostrich** [comment]
Yes, that works, but as you said, the controllers are too different for this to be a viable option. The Vive controllers are more like a wand (versus the pistol grip of the Quest controllers). As a result, pointing and aiming is very unnatural -- I have to be aiming around their knees to get a headshot.
