### ISSUE TITLE
Majority of games not launching in SteamVR mode when emulating Oculus headset

### ISSUE THREAD

**Issue by ndemie** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#82]
I'm using an Oculus Quest 2. 

I can connect to the headset just fine. I also see SteamVR on the headset without any issues. 

However when I try to launch games SteamVR will show "Next Up" and then a blank (SteamVR spacey room) screen. The game will be launched on my monitor in non-VR mode. This is the case for 80% of the games in my library, the other 20% work fine. 

I've noticed that when I switch the emulation mode from Oculus Rift CV1/S to Vive (Pro) the games launch fine. However the controller mapping is obviously not ideal. 

Anyone has any clue whats going wrong? Tried to reinstall SteamVR but that didn't do the trick

**Comment by GennadiyAMD** [comment]
@ndemie - There's a number of games that bypass the OpenVR API and go directly to the Oculus API, even when running under Steam, when they detect an Oculus headset. The fact that they launch fine when you switch emulation to a Vive headset is a strong argument for this being the case. And let me guess, all these games that don't start correctly are also available in the Oculus Store, not just Steam.

Not much can be done about this since we can't control what games are doing, unfortunately, aside from hacking the Oculus driver in Steam and replacing the Oculus runtime with our own module. But this would certainly break things like Oculus Link or Rift S/CV1, we can't be this intrusive.

I know this is not the answer you'd like to hear, but unfortunately that's what the reality is.
