### ISSUE TITLE
Support for 90Hz on Quest 2?

### ISSUE THREAD

**Issue by xjz5888** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#85]
With the new V23 software of Quest 2, is that possible to update the 90hz option on ReLive VR?

https://developer.oculus.com/blog/-oculus-quest-v23-how-to-update-your-app-for-90hz/

**Comment by AmishGuyWithWiFi** [comment]
I am also eagerly awaiting this... Virtual desktop doesn't play perfect with my AMD card, while ReLive VR works basically flawlessly. I was hoping there was a setting somewhere to change this in a file/etc, but haven't been able to find anything.

**Comment by GennadiyAMD** [comment]
@AmishGuyWithWiFi - version 1.0.25 enables 90Hz on Quest2, please try it.

**Comment by AmishGuyWithWiFi** [comment]
> @AmishGuyWithWiFi - version 1.0.25 enables 90Hz on Quest2, please try it.

@GennadiyAMD , this still does not work. Whether loading through Sidequest app store or the APK straight off github. Running newest 20.12.1 driver that dropped today. Whether I choose Rift S or CV1 in Radeon settings, with the new APK loaded its still reporting (and looking like) 75Hz in SteamVR. Maybe I'm missing something or doing something wrong, not sure. Any advice? Also went to SteamVR beta just to rule that out.

**Comment by GennadiyAMD** [comment]
@AmishGuyWithWiFi - a few questions:
- Which GPU are you running on? Is it one of the RX480/RX580/RX590 family?
- What resolution are you running at?
- Have you changed the default codec?
- Which title are you measuring the frame rate on? Can you achieve 90fps while running Steam Home?
- Are you seeing 75Hz or 72Hz in SteamVR? (click on the three horizontal lines in the upper-left corner of SteamVR to open the menu and check "Display Performance Graph" - once you close the menu, SteamVR would draw a graph and report the actual measured FPS at the bottom of the window). Do you see anything higher than 72 Hz there? 
- Could you please attach a log from c:\Program Files (x86)\Steam\logs\AMDWirelessVR.log - please make sure that you actually connect the headset before capturing the log, then zip it and just drag-and-drop into the response box.
- Could you also attach a dxdiag log? (just type 'dxdiag' in your command line window and click on Save All Information)

Thanks!

**Comment by AmishGuyWithWiFi** [comment]
- RX5600XT

- In the game I'm trying to play (Project Cars 2) I am running a mirror resolution of 1280x720 on my external display. The resolution I input into the web portal / server is 2496 x 2592, which from my research would represent "High" resolution on a Quest 2. Correct me if I am wrong here please. 

- I am running the HEVC codec forced in the web app only because I have experienced much worse performance since trying to play VR using the H.264 codec. 

- In Steam Home it is reporting 75 Hz. The only app I have been able to achieve 90 Hz on my setup is Virtual Desktop, but like I said, I am not getting acceptable performance using this third party app (even with the nicer/correct refresh rate)

- 75 Hz. I will check the "Display Performance Graph" option now and respond back. I apologize, I am still fairly new to this environment, but technically adept enough to figure it out / try to help. 

- Let me run the game and I'll attach the log file after some troubleshooting / gameplay. Will report back.

- Will attach a dxdiag log as well.

Thank you for your quick reply!!!

**Comment by Dirro** [comment]
Tagging in with my specs as-well since it doesn't seem to be 90hz;

**Which GPU are you running on?**
5700XT
**What resolution are you running at?**
Auto Selected
**Have you changed the default codec?**
Not knowingly at-least
**Which title are you measuring the frame rate on? Can you achieve 90fps while running Steam Home?**
Not sure how to measure frame rate buy using Steam Home for the logs

**Are you seeing 75Hz or 72Hz in SteamVR?**  
![image](https://user-images.githubusercontent.com/63126620/101549804-4d449400-397c-11eb-8ead-61567ea11114.png)

**Do you see anything higher than 72 Hz there?**
No

**Could you please attach a log from c:\Program Files (x86)\Steam\logs\AMDWirelessVR.log - please make sure that you actually connect the headset before capturing the log, then zip it and just drag-and-drop into the response box.**
[AMDWirelessVR.log](https://github.com/GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR/files/5662383/AMDWirelessVR.log)


**Could you also attach a dxdiag log? (just type 'dxdiag' in your command line window and click on Save All Information)**
[DxDiag.txt](https://github.com/GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR/files/5662395/DxDiag.txt)

**Comment by AmishGuyWithWiFi** [comment]
@Dirro I see in your log Encode Resolution: 1440x1440@72fps, so that would make sense why yours is locked at 72. Mine says Encode Resolution: 1440x1440@90fps, but Steam VR reports 75 Hz. Meanwhile mine says Render Resolution: 2496x2592 which makes sense because that's what I set in the web server settings for Relive VR. You didn't change yours so it says Render Resolution: 1440x1440. I'm still fairly new to the VR resolution vs game resolution vs "per eye" resolution, so not sure why you'd want it to be so low (1440x1440) if the headset natively is higher than that.

**Comment by Dirro** [comment]
I don't see a reason why I'd need to change SteamVR off Auto to a higher resolution since that doesn't effect fps cap.

Also don't know where they said you need to tinker with the settings manually.

**Comment by AmishGuyWithWiFi** [comment]
Just a quick update, I tried turning everything off and on and reinstalled things just to make sure, now when I put my headset on the Steam performance overlay shows 90 Hz, but in game when you check on the headset, it lists 75 Hz, and it feels that much lower too. Maybe I'm crazy, not sure. Attached screenshot.
![130285630_421016179080416_150982693521741571_n](https://user-images.githubusercontent.com/75340877/101553530-6ea48080-397a-11eb-97a1-7dbe3f176d25.jpg)

**Comment by GennadiyAMD** [comment]
@Dirro - you seem to be still running the old client app on the headset. Update it to 1.0.25.

@AmishGuyWithWiFi - your headset is correctly reporting 90Hz support. You render resolution is unnecessarily high though, this is a per eye setting, so width and height should be the same, ideally. Also there's no value in going this high, especially with non-linear scaling turned on and encoder resolution set to 1440x1440. On RX5600 1600x1600 for both should be a good value. But even with your numbers I can reach 90fps on 5700XT and 5600 shouldn't be much different. Your performance seems to be limited by something else:
_2020-12-08 16:31:36.715     2C6C [NetworkServer]    Info: Average latency: full 40.59(average 40.19) client 19.49 server 18.43 encoder  6.61 network  2.68 decoder  7.25, frame time **11.63 ms**_ - this is a good number corresponding to about 90fps. But later I'm starting to see this:
_2020-12-08 16:32:36.190     2C6C [NetworkServer]    Info: Average latency: full 66.34(average 43.62) client 23.95 server 37.67 encoder 22.43 network  4.72 decoder  9.36, frame time **15.69 ms**_ - this is too high. It goes down somewhat, but this doesn't look right.

Let me investigate this, I'll get back to you shortly. In the meantime, try resetting everything to default - simply delete (or rename) the %LOCALAPPDATA%\AMD\OpenVR\settings\settings.json and run SteamVR again - this file will get re-created with the defaults.

The graph is SteamVR on your monitor shows the actual refresh rate. What you see in the last screenshot (75Hz) shouldn't really matter, this is just the initial value reported to Steam before the headset connects, but once it connects, it the value shown in the little SteamVR window (the one where you see the icons for the headset and controllers) is what matters. Let's limit it to Steam Home for the time being since this 'game' is very lightweight and should not be the bottleneck.

**Comment by Dirro** [comment]
@GennadiyAMD So I was using SideQuest to download it didn't even think about it being possibly outdated.

Basically what happened to me;
1) SideQuest download & install revive through them
2) Can't get it to go 90Hz until you pointed out it was the outdated version
3) Grab APK directly from github and use that as a install and it works fine

I decided to try again to make sure and reinstalling the version from SideQuest goes back to the old version for some reason. But anyway thanks for the help 😄 😄 😄 😄

**Comment by AmishGuyWithWiFi** [comment]
@GennadiyAMD That is a wealth of information, thank you so much for your time. I am going to try the 1600 x 1600 setting you suggested and delete the settings file and try again. 

Also, I was doing a 30 car nascar race on pCars 2, after reading that is probably very, very demanding (more cars), I dropped to 10 and it seems much smoother. I'm thinking my 9700k may be bottlenecking with too much going on, but not sure. 

I will respond back with any findings but for now, thank you so much for your help. I really appreciate it!

**Comment by GennadiyAMD** [comment]
@Dirro - ahh, that means the release on github that SideQuest is linked to is broken. That should be easy to fix.

@AmishGuyWithWiFi - it could very well be that. Take a look at the Performance tab in Windows Task Manager while running the game - look at the CPU load and the GPU load (3D and Compute queues), see if anything is getting close to a 100% utilization. When the CPU is loaded to the brim, it would not submit GPU jobs quickly enough and then the GPU power management would kick in because there's no need for the GPU to run as fast, so you'd see everything slowing down. Might be worth looking at one of those new Ryzens - just kidding, 9700k is a fine CPU, but a CPU could definitely be one of the bottlenecks.

Glad this has all worked out for you folks! I'm going to close this for now, please don't hesitate to open a ticket if you run into any other issues. Good night!

**Comment by AmishGuyWithWiFi** [comment]
@GennadiyAMD heh, my last build was a 3700X. I never wanted to go Intel but with the component landscape right now coupled with ITX motherboards being scarce on the cheap end for AMD, I had to. I'm one of those people who've been proud to root for/buy AMD/ATI through tough times and watching what's playing out is so sweet. I just hope the supply/demand evens out sooner than later.

I just wanted to say I finally played a full hour though on VR for the first time in 2 weeks and your suggestions worked perfectly. I appreciate your expertise and help more than you know. I can finally enjoy my new rig! Thank you so much, and goodnight!

**Comment by GennadiyAMD** [comment]
@Dirro - SideQuest fixed.

**Comment by GennadiyAMD** [comment]
@AmishGuyWithWiFi - thank you for your kind words and it is my pleasure. Enjoy!

**Comment by renzhezhu1234** [comment]
Has anyone solved that? I download 1.0.25 , but it still showed 75 hz on  mu quest2.

**Comment by renzhezhu1234** [comment]
i solved that , it's a display bug. The real Hz is 90.
