### ISSUE TITLE
No VR Streaming Tab in Radeon Pro Settings

### ISSUE THREAD

**Issue by gregwym** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#95]
I'm using 2019 MacBook Pro 16" with AMD Radeon Pro 5500M. The Radeon Pro software is version 20.10.26.01 and has been clean installed. I also have Steam and SteamVR installed properly and I'm able to play VR thru usb cable to my Quest 2. 

After installed the Radeon Pro software, I'm able to access the ReLive settings thru the notification "Radeon Pro ReLive has been successfully installed". But after I turned on the ReLive feature, there is no "Game & VR Streaming" tab. It only shows four tabs "General", "Live Stream", "Recording" and "Scene". 

How can I gain access to the "VR Streaming" tab?

![image](https://user-images.githubusercontent.com/510089/107134777-fee34100-68a9-11eb-8a50-2958d0614c51.jpeg)

**Comment by GennadiyAMD** [comment]
@gregwym - Windows on a Mac isn't really an officially supported configuration. Check if you have the WVR folder under c:\Program Files\AMD, if you do, then you might be in luck, but if not, the feature is not getting installed on this configuration.

**Comment by gregwym** [comment]
<img width="399" alt="image" src="https://user-images.githubusercontent.com/510089/107338765-c772c100-6a70-11eb-835e-a469d37d77ac.png">
Yes, `WVR` folder exists. Tho I can still not see the "Game & VR Streaming" tab. Is there anything else I can check to further diagnostic? 

Mean while, I also tried the Live Streaming feature and I could not get it to capture my desktop or game play window properly. The audio works, but video is either black or green screen. 
You can watch the Twitch replays here: https://www.twitch.tv/videos/905538829?filter=archives&sort=time

**Comment by GennadiyAMD** [comment]
@gregwym - then you're lucky :) Go into this folder, inside there should be the OpenVR folder, inside there're two .cmd files: registerdriver.cmd and unregisterdriver.cmd. Just double-click on registerdriver.cmd and this will enable SteamVR integration. Unregisterdriver.cmd performs the opposite action and disables SteamVR integration. They're completely equivalent to flipping the SteamVR integration switch in Radeon Settings. You can live without the UI in Radeon Pro Settings by following [these instructions](https://github.com/GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR/wiki/Advanced-Configuration-Using-a-Web-Browser) - note that Web UI would only be available while SteamVR is running in this case, but it would still allow you to use the feature.

Live Streaming is a separate feature not related to ReLive VR - it's not for VR games. I will pass this on to the respective team that handles this feature.

On a separate note, have you tried running the latest consumer driver rather than the Pro driver? Consumer drivers have a much more frequent release cadence and some of these problems may have been resolved already. You should be able to install the consumer driver on a Pro GPU without any trouble. If you don't need any of the Pro driver features, this might be a better approach.

**Comment by gregwym** [comment]
![image](https://user-images.githubusercontent.com/510089/107414656-295e1580-6ac7-11eb-9e14-ed1976fb3933.jpeg)

Re: consumer driver

I have tried all these versions and they all won't install. I think only the one made specifically for Apple Bootcamp can be installed. 

I'm trying https://www.bootcampdrivers.com/ atm.

**Comment by GennadiyAMD** [comment]
@gregwym - bummer with that :( But either way, running the the registerdriver.cmd script manually should get you going with ReLive VR.

Thanks for reporting this!

**Comment by gregwym** [comment]
I gave a try to https://www.bootcampdrivers.com/. I successfully installed the consumer edition (red gaming edition) driver. However, it still doesn't show the Game & VR Streaming tab either. Even the ReLive Streaming tab disappeared. 

Following that, I tried `registerdriver.cmd`. I managed to streamed SteamVR games to my Quest 2, but for some reason the audio is delayed for about 1-2 seconds than the video. Beat Saber was not playable with this level of delay. 😞 With the same networking setup, ALVR works perfectly. I guess I will stick with ALVR for now. 

Thank you for all the help!
