### ISSUE TITLE
Feature request: Allow for higher video bitrates in web UI

### ISSUE THREAD

**Issue by pbsds** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#98]
Relive VR is so far a great solution, and is currently my go-to method for untethered VR. 

I believe however my home network should be able to support higher video bitrates than 100Mpbs. Those who made their way all the way to the web UI should be allowed to configure custom bitrates as long as this does not break any restrictions in the hardware video encoder. (I'm using a RX580)

![image](https://user-images.githubusercontent.com/140964/109335646-a0830000-7862-11eb-8f3d-ac11366620da.png)

I am not asking you to enable users to configure higher bitrates in the Radeon Software UI, as that could be a major foot-gun which could damage Relive VRs reputation, but for those of us who went out of their way to bypass the recommended settings it should be an option possible to play around with.

**Comment by pbsds** [comment]
Nah

**Comment by GennadiyAMD** [comment]
@pbsds - Peter, I didn't understand the comment :) I didn't respond right away because this would involve a change in the driver, not the client app. Driver releases follow their own schedule, which I cannot easily change due to extensive QA cycles and other reasons. Client app is easier, but bitrate is controlled on the server. So there was nothing to say at the moment, but rest assured that your request has been noted and is already implemented - it's just not going to be in the next driver release because we missed the release window - you will be able to set up to 170Mbps by editing settings.json.

As a side note - 100Mbps maximum was chosen based on practical observations. The WiFi bandwidth is a tricky thing, it is all "up to XXXMbps" and whatever the  bandwidth your router claims is a combined bandwidth for multiple devices, not the speed of a single connection. Once you start going above 100Mbps, the hiccups during transmission become much more frequent to the point of becoming noticeable, especially on scenes where motion not related to head movements is present. I rollercoaster game is a good example of that. You start seeing these momentary freezes that asynchronous time warp cannot compensate and they really break immersion. On the other hand, an increase in image quality because of less compression becomes diminishingly small - one can visually tell the difference between 50Mbps and 100Mbps, but you really need to look hard to tell 100Mbps from 120Mbps. So 100Mbps looks like a good trade-off. 

Hopefully this answers it ;)

**Comment by pbsds** [comment]
Thanks for the response. Well researched and to the point.

> ... one can visually tell the difference between 50Mbps and 100Mbps, but you really need to look hard to tell 100Mbps from 120Mbps

This was the reason I decided to close the issue. The gain in visual fidelity would be negligible. I don't really experience noticeable artefacts on 100Mbps.

My original goal in increasing the bandwidth was to non-intuitively decrease the time to encode the video.  The idea was based on performance metrics recorded in ALVR, which had the time to encode the video dominate all other sources of delay. Even the transmission delay which was miniscule in comparison. Seeing a limit being put the knob I wanted to tweak was what prompted me filing this issue.

Since then I've concluded that ReLive VR in my experience already has less of a delay than ALVR, probably employing a more efficient video encoding pipeline. Thanks for your great work and I am looking forward to any updates. :)

**Comment by GennadiyAMD** [comment]
@pbsds - encode time depends mostly on resolution, not bitrate - the higher the resolution, the longer it takes to encode a frame. Bitrate has virtually no effect on encoding time, but since you send more data at higher bitrates, transmission over the network would take longer. So if your goal is to reduce latency, increasing the bitrate would be working against you, not for you. Mind you, the difference would be rather small, around 1-1.5 ms, that's going from 50Mbps to 100Mbps, but adding another 20-30Mbps on top of that was causing more spikes in transmission time that I was talking about in my previous response.

But you're absolutely correct that most latency comes from encoding and decoding, not transmission. So if your goal is to minimize latency, then Navi+Quest2 combination is your friend. Navi (RX6800/6900) has a significantly faster encoder compared to Vega and Polaris (RX590/580/480/470) and Quest2 has a significantly faster decoder compared to the original Quest. Or you can try to drop the encoder resolution to about 1280x1280 per eye - anything below that looks blurry, but this could buy you a few ms of latency.
